config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/fb' => 'home#fb'
  post '/fb' => 'home#fb'
  get '/results/:id' => 'home#results'

  scope '/api' do
    resources :relations
    resources :parties
    resources :users
    resources :votes

    scope '/votes' do
      get '/results/:user_id' => 'votes#results'
      get '/user/:user_id'    => 'votes#user'
    end

    scope '/connect' do
      post '/' => 'connect#create'
      get  '/user/:fb_id' => 'connect#user'
    end

    scope '/stream' do
      post '/post/:user_id' => 'stream#post'
      get  '/user/:user_id' => 'stream#user'
      get  '/flat/:user_id' => 'stream#flat'
      get  '/party/:party_id' => 'stream#party'
    end

  end

end

app/models/party.rb
class Party < ActiveRecord::Base
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  # GET /parties
  # GET /parties.json
  def index
    # Cache response
      @parties = Party.all
      expires_in(1.days, public: true)
      # logger.info "Parties Cached"
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>