config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/fb' => 'home#fb'
  post '/fb' => 'home#fb'
  get '/results/:id' => 'home#results'

  scope '/api' do
    resources :relations
    resources :parties
    resources :users
    resources :votes

    scope '/votes' do
      get '/results/:user_id' => 'votes#results'
      get '/user/:user_id'    => 'votes#user'
    end

    scope '/connect' do
      post '/' => 'connect#create'
      get  '/user/:fb_id' => 'connect#user'
    end

    scope '/stream' do
      post '/post/:user_id' => 'stream#post'
      get  '/user/:user_id' => 'stream#user'
      get  '/flat/:user_id' => 'stream#flat'
      get  '/party/:party_id' => 'stream#party'
    end

  end

end

app/models/relation.rb
class Relation < ActiveRecord::Base
	belongs_to :user
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:user_id, :friend_user_id)
    end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/index.html.erb
<h1>Listing relations</h1>

<table>
  <thead>
    <tr>
      <th>Fbuser</th>
      <th>Friend fbuser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.user_id %></td>
        <td><%= relation.friend_user_id %></td>
        <td><%= link_to 'Show', relation %></td>
        <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
        <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fbuser:</strong>
  <%= @relation.user_id %>
</p>

<p>
  <strong>Friend fbuser:</strong>
  <%= @relation.friend_user_id %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>